gluten_containing_ingredients = [
  'gluten', 'wheat', 'barley', 'rye', 'triticale', 'farina', 'semolina', 'spelt', 'bulgur', 
  'durum', 'graham flour', 'kamut', 'einkorn wheat', 'malt', 'malt flavoring', 'malt vinegar',
  'malt extract', 'malt syrup', 'malt powder', 'maltodextrin', 'modified wheat starch', 
  'wheat bran', 'wheat germ', 'wheat starch', 'hydrolyzed wheat protein', 
  'hydrolyzed wheat starch', 'vital wheat gluten', 'brewer s yeast', 'couscous', 'wheat berries',
  'wheat gluten', 'emmer', 'farro', 'fu', 'graham', 'matzo', 'matzo meal', 'seitan', 'udon',
  'panko', 'orzo', 'atta', 'frumento', 'maida', 'matzah', 'tabbouleh', 'gluten', 'gliadin',
  'barley malt', 'malted milk', 'malted barley', 'malt extract', 'maltose',  'barley flour', 
  'barley grass', 'barley flakes', 'barley pearls', 'malted barley flour', 'rye bread', 
  'rye flour', 'rye meal', 'rye flakes', 'rye berries', 'triticale flour', 'triticale grains', 
  'triticale berries', 'triticale flakes', 'brown rice syrup', 'wheat based soy sauce', 
  'imitation seafood', 'artificial crab', 'seasoned rice vinegar', 'modified food starch',
  'soy sauce', 'tamari', 'wheat based dextrin', 'wheat based glucose syrup', 
  'wheat based maltodextrin', 'wheat based natural flavoring', 'wheat based starch', 
  'wheat based vinegar', 'hydrolyzed vegetable protein'
]

lactose_containing_ingredients = [
  'milk', 'cream', 'butter', 'buttermilk', 'cheese', 'yogurt', 'whey', 'whey protein', 
  'lactose', 'milk solids', 'milk powder', 'nonfat dry milk', 'evaporated milk', 
  'condensed milk', 'goat milk', 'cow milk', 'sheep milk', 'casein', 'caseinates', 
  'curds', 'dry milk solids', 'ghee', 'milkfat', 'cream cheese', 'cottage cheese', 
  'sour cream', 'creamer', 'ice cream', 'custard', 'milk chocolate', 'milk protein',
  'milk protein concentrate', 'milk protein isolate', 'skim milk', 'whole milk', 
  'whey protein concentrate', 'whey protein isolate', 'ricotta', 'powdered milk', 
  'kefir', 'quark', 'crème fraîche', 'lactalbumin', 'lactoglobulin', 'malted milk', 
  'butter oil', 'milk derivative', 'milk solids non fat', 'milk solids not fat',
  'dry milk powder', 'yogurt powder', 'lactose monohydrate', 'lactose anhydrous', 
  'cream powder', 'milk sugar', 'galactose', 'whey powder', 'milk solids not fat', 
  'dried whey', 'dry cream', 'dry buttermilk', 'milk crumb', 'sweetened condensed milk', 
  'lactoferrin', 'lactose hydrolyzed', 'milk peptides', 'milk fraction', 
  'lactose concentrate', 'lactose free milk', 'nonfat milk solids', 'hydrolyzed milk protein', 
  'dry whole milk', 'liquid milk', 'milk replacer', 'artificial butter flavor', 
  'butter flavoring', 'natural butter flavor', 'milk blend', 'milk by product', 
  'milk mineral', 'milk permeate', 'milk protein blend', 'milk syrup', 'nonfat milk', 
  'recombined milk', 'reconstituted milk', 'reduced fat milk', 'soft cheese', 'sour milk', 
  'sweet milk', 'milk based ingredients', 'fermented milk', 'milk derived ingredients', 
  'milk based cream', 'milk based powder'
]

non_vegetarian_ingredients = [
  'chicken', 'beef', 'pork', 'lamb', 'goat', 'turkey', 'duck', 'fish', 'shellfish', 
  'shrimp', 'crab', 'lobster', 'clams', 'oysters', 'mussels', 'squid', 'octopus', 
  'anchovies', 'sardines', 'tuna', 'salmon', 'cod', 'trout', 'mackerel', 'herring', 
  'scallops', 'bacon', 'ham', 'prosciutto', 'sausage', 'pepperoni', 'salami', 
  'meat broth', 'bone broth', 'gelatin', 'lard', 'suet', 'tallow', 'meat extract',
  'beef extract', 'pork extract', 'fish sauce', 'oyster sauce', 'worcestershire sauce',
  'caviar', 'roe', 'fish oil', 'fish gelatin', 'meat fat', 'animal fat', 'chicken fat', 
  'duck fat', 'beef fat', 'goose fat', 'bone marrow', 'foie gras', 'meat stock',
  'chicken stock', 'beef stock', 'pork stock', 'meat gravy', 'chicken gravy', 
  'beef gravy', 'meat based flavoring', 'chicken based flavoring', 'fish based flavoring',
  'pork based flavoring', 'meat concentrate', 'poultry', 'game meat', 'venison', 
  'rabbit', 'quail', 'pheasant', 'snake', 'frog legs', 'alligator', 'kangaroo', 
  'bison', 'elk', 'boar', 'veal', 'tripe', 'sweetbreads', 'liver', 'kidneys', 
  'heart', 'giblets', 'blood sausage', 'black pudding', 'haggis', 'liver pate',
  'meat pie', 'meat pâté', 'chorizo', 'bratwurst', 'blood pudding', 'head cheese', 
  'spam', 'corned beef', 'pastrami', 'peppered beef', 'biltong', 'jerky', 'bresaola',
  'biltong', 'biltong', 'biltong', 'biltong', 'biltong', 'biltong', 'biltong',
  'meatball', 'meatloaf', 'chicken nuggets', 'chicken wings', 'chicken drumsticks', 
  'chicken breast', 'chicken thighs', 'turkey breast', 'turkey drumsticks', 
  'turkey wings', 'fish fillet', 'fish sticks', 'crab meat', 'crab sticks', 
  'shrimp paste', 'prawn crackers', 'eel', 'grouper', 'halibut', 'haddock', 
  'snapper', 'swordfish', 'tilapia', 'turbot', 'sole', 'bass', 'clams', 
  'cockles', 'barnacles', 'conch', 'crayfish', 'langoustine', 'periwinkle', 
  'whelks', 'abalone', 'geoduck', 'catfish', 'mussels', 'scampi', 'surimi', 
  'beef jerky', 'chicken jerky', 'duck jerky', 'pork jerky', 'salmon jerky', 
  'turkey jerky', 'veal stock', 'meat based soups', 'fish based soups', 
  'chicken soup', 'beef soup', 'meat stew', 'beef stew', 'pork stew', 
  'seafood stew', 'paella', 'gumbo', 'jambalaya', 'bouillabaisse', 'cioppino',
  'chicken liver', 'pork liver', 'beef liver', 'calf liver', 'liverwurst', 
  'liver sausage', 'chicken feet', 'chicken gizzard', 'beef tongue', 'ox tongue',
  'pig s feet', 'pig s ears', 'pig s tail', 'oxtail', 'rocky mountain oysters',
  'testicles', 'brains', 'offal', 'organ meat', 'animal rennet', 'rennet', 
  'chicken liver pâté', 'foie gras pâté', 'fish pâté', 'duck pâté', 'goose pâté',
  'charcuterie', 'meatloaf', 'steak tartare', 'carpaccio', 'bacon bits', 
  'pork rinds', 'chicharrón', 'crispy pork', 'bacon fat', 'pork belly',
  'goose liver', 'fish roe', 'fish eggs', 'roe', 'katsuobushi', 'bonito flakes',
  'scallop', 'octopus balls', 'squid rings', 'calamari', 'surimi', 'fish flakes',
  'fish meal', 'fish cake', 'crab cake', 'shrimp chips', 'clam juice', 
  'clam chowder', 'fish soup', 'lobster bisque', 'crab bisque', 'fish sticks', 
  'crab sticks', 'imitation crab', 'seafood mix', 'seafood platter', 
  'seafood cocktail', 'tuna salad', 'chicken salad', 'beef salad', 
  'seafood salad', 'surf and turf', 'chicken kebab', 'beef kebab', 
  'pork kebab', 'lamb kebab', 'seafood kebab', 'duck confit', 'goose confit', 
  'rabbit stew', 'lamb stew', 'pork chops', 'beef ribs', 'pork ribs', 
  'baby back ribs', 'spare ribs', 'pork belly', 'brisket', 'short ribs', 
  'prime rib', 'beef roast', 'pork roast', 'lamb roast', 'beef tenderloin', 
  'pork tenderloin', 'venison stew', 'game meat', 'rabbit meat', 'frog legs',
  'alligator meat', 'snake meat', 'escargot', 'snails', 'quail eggs', 
  'duck eggs', 'fish eggs', 'caviar', 'roe', 'liver pâté', 'meat pâté',
  'fish pâté', 'poultry pâté', 'poultry based ingredients', 'meat based ingredients',
  'seafood based ingredients'
]

